version: "3"

services:
  web-presenter:
    image: sebastian2410/web-presenter
    restart: unless-stopped
    container_name: web-presenter
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:80
    environment:
      ASPNETCORE_URLS: "http://*"
      ASPNETCORE_ENVIRONMENT: "Staging"
      DB__Server: "db"
      DB__Port: "5432"
      DB__Database: "WebPresenter"
      DB__User: "postgres"
      DB__Password: "psql"
  
  db:
    image: postgres:12
    restart: unless-stopped
    container_name: web-presenter-db
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "psql"
      POSTGRES_DB: "WebPresenter"
