version: "3"

services:
  web-presenter:
    image: web-presenter
    restart: unless-stopped
    container_name: web-presenter
    depends_on:
      - db
    links:
      - db
    ports:
      - 8080:80
    environment:
      ASPNETCORE_URLS: "http://*"
      ConnectionStrings__DB: "Server=db;Port=5432;Database=WebPresenter;User Id=postgres;Password=wasistpassiert;"
  db:
    image: postgres:12
    restart: unless-stopped
    container_name: web-presenter-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: wasistpassiert
      POSTGRES_DB: WebPresenter
